### ISSUE TITLE
Up our tables game

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/opsnap#6]
Table 3 currently is a bit basic:

|offence_simple        | Cyclist| Driver| Other| Total| Cyclist (%)| Driver (%)| Other (%)| Total (%)|
|:---------------------|-------:|------:|-----:|-----:|-----------:|----------:|---------:|---------:|
|Inconsiderate driving |    3713|    919|   360|  4992|        78.7|       14.9|      20.3|      39.4|
|Careless driving      |     517|   2147|   253|  2917|        11.0|       34.8|      14.3|      23.0|
|Other                 |     488|   3099|  1160|  4747|        10.3|       50.3|      65.4|      37.5|
|Total                 |    4718|   6165|  1773| 12656|       100.0|      100.0|     100.0|     100.0|

Can we do better? cc @rogerbeecham

**Comment by rogerbeecham** [comment]
Sorry Robin, getting errors when trying to call opsnap functions – can’t fine filter_nas() defined in the opsnap.R source:

Caused by error in `filter_nas()`:
! could not find function "filter_nas"

From: Robin Lovelace ***@***.***>
Date: Wednesday, 3 July 2024 at 10:33
To: ITSLeeds/opsnap ***@***.***>
Cc: Roger Beecham ***@***.***>, Mention ***@***.***>
Subject: [ITSLeeds/opsnap] Up our tables game (Issue #6)

CAUTION: External Message. Use caution opening links and attachments.

Table 3 currently is a bit basic:
offence_simple
Cyclist
Driver
Other
Total
Cyclist (%)
Driver (%)
Other (%)
Total (%)
Inconsiderate driving
3713
919
360
4992
78.7
14.9
20.3
39.4
Careless driving
517
2147
253
2917
11.0
34.8
14.3
23.0
Other
488
3099
1160
4747
10.3
50.3
65.4
37.5
Total
4718
6165
1773
12656
100.0
100.0
100.0
100.0

Can we do better? cc @rogerbeecham<https://github.com/rogerbeecham>

**Comment by Robinlovelace** [comment]
Reason: the function is not exported. My bad @rogerbeecham will fix:


``` r
devtools::install_github("itsleeds/opsnap"); opsnap::filter_nas
#> Using github PAT from envvar GITHUB_PAT. Use `gitcreds::gitcreds_set()` and unset GITHUB_PAT in .Renviron (or elsewhere) if you want to use the more secure git credential store instead.
#> Downloading GitHub repo itsleeds/opsnap@HEAD
#> 
#> ── R CMD build ─────────────────────────────────────────────────────────────────
#> * checking for file ‘/tmp/RtmpZyRIVT/remotes17f91753e855e7/ITSLeeds-opsnap-2fcb349/DESCRIPTION’ ... OK
#> * preparing ‘opsnap’:
#> * checking DESCRIPTION meta-information ... OK
#> * checking for LF line-endings in source and make files and shell scripts
#> * checking for empty or unneeded directories
#> * building ‘opsnap_0.0.0.9000.tar.gz’
#> Installing package into '/home/robin/R/x86_64-pc-linux-gnu-library/4.4'
#> (as 'lib' is unspecified)
#> Error: 'filter_nas' is not an exported object from 'namespace:opsnap'
```

<sup>Created on 2024-07-03 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by Robinlovelace** [comment]
Fix to the reproducibility issue in commit above. Can you try again @rogerbeecham ? Clearly code needed tires kicked so thanks for testing!

**Comment by rogerbeecham** [comment]
Yes all working. Have got some replacement gt() tables, with incell charts to show those % differences etc. How do you want me to push, don’t think I have write access to main branch?

Roger

From: Robin Lovelace ***@***.***>
Date: Wednesday, 3 July 2024 at 16:47
To: ITSLeeds/opsnap ***@***.***>
Cc: Roger Beecham ***@***.***>, Mention ***@***.***>
Subject: Re: [ITSLeeds/opsnap] Up our tables game (Issue #6)

CAUTION: External Message. Use caution opening links and attachments.

Fix to the reproducibility issue in commit above. Can you try again @rogerbeecham<https://github.com/rogerbeecham> ? Clearly code needed tires kicked so thanks for testing!

**Comment by Robinlovelace** [comment]
Write access just provided @rogerbeecham: https://github.com/ITSLeeds/opsnap/invitations Let's catch up tomorrow on this..

**Comment by Robinlovelace** [comment]
Updated version looks really nice:

![image](https://github.com/user-attachments/assets/e40cca78-036f-4434-a1a6-a52afa5d17e3)

**Comment by Robinlovelace** [comment]
Only issue @rogerbeecham is that it does not work in PDF format needed for submission:

```
updating existing packages
ERROR: 
compilation failed- error
Illegal unit of measure (pt inserted).
<to be read again> 
                   p
l.404 O
       ffence & \# records & \% records \\ 

```

**Comment by Robinlovelace** [comment]
Looking to save it as png: https://gt.rstudio.com/reference/gtsave.html#:~:text=gtsave()%20makes%20it%20easy,%2C%20LaTeX%2C%20or%20RTF%20file.
